### ISSUE TITLE
Incomplete README

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#1]
@N0taN3rd, In the readme you left a reference saying "[Modeled after this boiler plate](https://github.co" but it looks like the rest of the URL got clipped off. I'd fix it myself but don't know the URL you intended. ;)

**Comment by N0taN3rd** [comment]
@machawk1 Thank you for pointing this out.  Fixed in commit https://github.com/N0taN3rd/wail/commit/c2034eb63f194f8932268b3e6c065fc6534fd718
