### ISSUE TITLE
First launch on OS X causes JavaScript popup error

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#13]
3ce3f3fa5f84dbee72069d18b15ccaec06b05d85

![screen shot 2016-07-01 at 11 30 58 am](https://cloud.githubusercontent.com/assets/2514780/16527291/f213220a-3f83-11e6-97ad-643b7a266b0e.png)

**Comment by machawk1** [comment]
@N0taN3rd Is this popup's contents from same time back the same that we were getting today?

**Comment by N0taN3rd** [comment]
@machawk1 No it is not. I required a purely development library that fails 100% of the time when running in a production build. 

This was due my lack of understanding of where to put these dependancies properly and has been  rectified in this commit dc16e69
