### ISSUE TITLE
Problem connecting to local web server

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#20]
When trying to load the Heritrix web config and Wayback UI, I'm getting an error in Safari that it can't connect to the server 'localhost'.

I may not have a web server running, but I can't find where to turn it on.  I looked in SysPrefs> Sharing, but it's no longer there (running Yosemite).

There may need to be a check somewhere that the local web server is running and letting the user know they need to enable it.

**Comment by machawk1** [comment]
@weiglemc The user should not have to explicitly start a web server on their system, WAIL's "web servers" are the webUIs for Heritrix and Wayback.

I installed WAIL-Electron RC-1, set Safari as my default browser, clicked the "View Wayback in Browser" button and am shown the attached.
![screen shot 2016-07-27 at 10 34 44 am](https://cloud.githubusercontent.com/assets/2514780/17179056/d01d218e-53e5-11e6-83ce-8b7039597ab9.png)

Clicking "Launch Web UI" for Heritrix gives me the "Potential Phishing Site" warning, which is a "feature" of Heritrix. Clicking continue then shows this dialog:
![screen shot 2016-07-27 at 10 37 19 am](https://cloud.githubusercontent.com/assets/2514780/17179163/2acb2fa4-53e6-11e6-8c25-6d7718d657a7.png)
but then I am asked for credentials. Entering the correct credentials (lorem:ipsum) brings me to the Heritrix UI but we can't expect a user to do this, know these credentials, or be wary of a site that gives the phishing warning. This loss of credentials as part of the UI only seems to be an issue with Safari.

**Comment by N0taN3rd** [comment]
closing per 1.2.0-beta2
