### ISSUE TITLE
Perform UX sanity checks before firing off crawl.

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#24]
Related to #23, warn a user if they hit the START CRAWL button without having entered any URIs to crawl. The styling and functionality for the text boxes on this field, while fancy, are deceptive. If a user clicks on "Enter URI to crawl" and sees the placeholder already there, they might assume that this is the default value and not a guide to the format expected. The same goes with the "Enter Crawl Depth" field, except I presume that you use this placeholder value ("1") as the value for crawl depth in the job if not specified.

**Comment by machawk1** [comment]
Related but different than #18.

**Comment by N0taN3rd** [comment]
@machawk1 Yes I do use a default value of 1 and to your point it is a best practice for that to be indicated which I have neglected until now. 

Thanks for pointing that!
