### ISSUE TITLE
Remove UI padding

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#3]
@N0taN3rd Is it possible to remove the padding around the UI within the window?

![ww](https://cloud.githubusercontent.com/assets/2514780/16382817/6cd66bf0-3c50-11e6-9a6d-a00eaf7cdb29.png)

![wailfront](https://cloud.githubusercontent.com/assets/2514780/16382797/5145d90c-3c50-11e6-9f57-fc57e59d8bfc.png)

**Comment by N0taN3rd** [comment]
@machawk1 Yes it is. I was using a Paper element with a zdepth of 3ish to give it some depth

**Comment by machawk1** [comment]
@N0taN3rd On OS X, all windows have a drop shadow, so the redundant drop shadow looks strange. I think retaining the padding of the elements from the window edge is good (unlike img 2 above). @ibnesayeed might know of other ways to achieve some "depth" in the UI.

**Comment by N0taN3rd** [comment]
@machawk1 thank you for letting me know about that I was not aware.

**Comment by ibnesayeed** [comment]
I might be able to comment on it when I see it live, perhaps when you visit the office next time.`

**Comment by machawk1** [comment]
I tried building from source to get you a screenshot of the double drop shadow, @N0taN3rd, but #4 prevented me from doing so. Regardless, the "empty" window in the attached shows you the native drop shadow effect in OS X.

![screen shot 2016-06-27 at 3 33 35 pm](https://cloud.githubusercontent.com/assets/2514780/16392957/93565304-3c7c-11e6-8ac5-c40983d6005e.png)

**Comment by machawk1** [comment]
Fixed as of fdf9a65f4466254d73dbc06df88d696f1cc07670.
