### ISSUE TITLE
UI not changed when Heritrix KILL button pushed

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#34]
I hit the kill button in the Service Status interface and the UI does not change. I can try the web UI I had open previously and it is no longer accessible but nothing in the WAIL UI shows a status change. Even if it's a pending operation, something ought to change in the UI to indicate that the process is either in the process of being shutdown (e.g., change KILL button to KILLING...) or if the process is complete, the FIX button ought to be activated.

Based off of 7747d50068fb9fa68ee70205b08dd003ae803acf built from src, OS X.

**Comment by N0taN3rd** [comment]
@machawk1 Per the changing of the status buttons they are tied to when WAIL detects actual changes. I am hesitant to modify the buttons text(due to some error incurred when starting up a service could leave them in a funky state) would using the notification system already in place suffice?

**Comment by machawk1** [comment]
@N0taN3rd Are the buttons meant to be actionable? A user will likely push the button, see no change/notification in the UI and click it again. Using the notification system might help with this but so long as the UI stays as it was before, it's encouraging the user to repeat the action. Would it be possible to change the "style" of the button until the process completes? GitHub and Gmail do something like this.

**Comment by N0taN3rd** [comment]
@machawk1 Using styling would be easier and would decrease the number of state transitions the button components would have to go through. 

Here's a thought. Using some of the unused space at the bottoms of the screen to display that kind of informational messages would allow for expressive informational error messages. Starting up Restarting Heritrix -> Heritrix is now operational etc. I have this functionality in the big stop the presses dialogue displayed when this situation happens and can easily add it directly to the services screen.

**Comment by machawk1** [comment]
@N0taN3rd Styling and expressive informational errors 👍
