### ISSUE TITLE
Menu weirdness on OS X

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#35]
Based off of 7747d50068fb9fa68ee70205b08dd003ae803acf built from src on OS X. Current menus:

File > Settings
Setting should be under wail menu, see Chrome:
![screen shot 2016-08-03 at 5 26 35 pm](https://cloud.githubusercontent.com/assets/2514780/17382554/7605e7ac-599f-11e6-8b18-1537bb5a0b4f.png)

View > Close, Minimize, Zoom, Bring All to Front
These options should all be under the "Window" menu
Chrome's View:
![chromeview](https://cloud.githubusercontent.com/assets/2514780/17382615/c03b2756-599f-11e6-8675-d06b97944539.png)
Finder's Window menu:
![screen shot 2016-08-03 at 5 29 14 pm](https://cloud.githubusercontent.com/assets/2514780/17382638/d78a4680-599f-11e6-8c33-a28ed57e2493.png)

**Comment by N0taN3rd** [comment]
@machawk1 done

**Comment by machawk1** [comment]
All looks well from a fresh pull, build, and execute for this issue.
