### ISSUE TITLE
Receive error in accessing local HTML files in OS X binary

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#4]
I built from source on OS X 10.11.4 based off of 3ce3f3fa5f84dbee72069d18b15ccaec06b05d85 . When I launch the binary in the releases folder, I get none of the normal blue-and-white WAIL-Electron components but do get two windows with different errors in the console.
- Not allowed to load local resource: file:///src/background/monitor.html
- Not allowed to load local resource: file:///src/wail.html

**Comment by N0taN3rd** [comment]
Yes the two windows is to catch errors just like that. And is interesting that the pathing is  a problem. 
The second window is the monitor page and in the man file I(was) getting the parent path for the folder the electron-main was in.  Investigating again

**Comment by N0taN3rd** [comment]
@machawk1 switched the resource path finding in commit  dd741e2 as well as ensure only the main window is open but with dev tools so any errors can be seen
Please pull and try again.

**Comment by machawk1** [comment]
@N0taN3rd Checked again, different machine (OS X 10.11.5) based on 3ce3f3fa5f84dbee72069d18b15ccaec06b05d85 . The WAIL UI is displayed without showing the console and errors when the binary is built using `npm run-script package`.
