### ISSUE TITLE
Force index option

### ISSUE THREAD

**Issue by N0taN3rd** [N0taN3rd/wail#45]
When users add a warc file an option to force indexing should be added thus not relying on our timed indexing to happen

**Comment by weiglemc** [comment]
I'm still having problems with WAIL not reindexing WARCs that I put in the archives folder.  I can see that it's creating and updating the index.cdx file, but the URI that I archived doesn't appear in Wayback.

Here's the URL that I captured with WarcCreate:
https://www.facebook.com/LADOTD/videos/vb.74154292700/10154040426997701/?type=2&theater

There's nothing in the index file that references the 20160822193710321.warc file. The odd thing is that as I watch the archiveIndexes folder, there's a 20160822193710321.cdx file that's created.

The WARC is too big for me to email, put on the wiki, or put here, so I've put it and the index that was just created in a shared Box folder.  I'll email you and Mat the link.

**Comment by machawk1** [comment]
@N0taN3rd What tool / script are you using to generate the cdx files?

@weiglemc Do you experience the same thing with WARCs from other sources? Pending @N0taN3rd 's testing of the files you supplied, if WAIL generates a CDX with the expected contents with WARCs from sources other than WARCreate, we may need to look into this as a bug in the latter.

**Comment by N0taN3rd** [comment]
![drweiglewarc](https://cloud.githubusercontent.com/assets/8648317/17949803/1e9c11e4-6a25-11e6-8b34-97879b471c7a.png)
@weiglemc @machawk1 
Currently I am using the cdxindexer script from bundledApps/tomcat/webapps/bin/cdxindexer
Then executing `export LC_ALL=C; sort -u ${settings.get('cdxTemp')} > ${settings.get('indexCDX')}` as was done before. 

Pywb when using its cdx-indexer with the all records option used produced the error seen in the above image.  

WAIL will be using pywb for indexing after today as I am currently integrating it  beyond dev testing builds will follow when this process is complete

**Comment by weiglemc** [comment]
I added a couple more files to the shared directory:

20160822124809108.warc - also created by WC but was indexed and replays in WAIL-Wayback

fb-video-20160825125032.warc - created by webrecorder.io, not indexed by WAIL-Wayback

And I added the latest index.cdx generated by WAIL-Wayback.

-Michele

On Aug 24, 2016, at 5:41 PM, Mat Kelly <notifications@github.com<mailto:notifications@github.com>> wrote:

@N0taN3rdhttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fN0taN3rd&data=01%7c01%7cmweigle%40cs.odu.edu%7cb9bbf970836e444eace808d3cc677abb%7c48bf86e811a24b8a8cb368d8be2227f3%7c0&sdata=r7Iaz72zblFVEZkFSQe8zETtwWp%2bmbu8XFMJwVokR2I%3d What tool / script are you using to generate the cdx files?

@weiglemchttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fweiglemc&data=01%7c01%7cmweigle%40cs.odu.edu%7cb9bbf970836e444eace808d3cc677abb%7c48bf86e811a24b8a8cb368d8be2227f3%7c0&sdata=Q5pMmTRR%2b7c%2bKX2D1D7uzPlWu3pYu7%2f765mu8Usqq5U%3d Do you experience the same thing with WARCs from other sources? Pending @N0taN3rdhttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fN0taN3rd&data=01%7c01%7cmweigle%40cs.odu.edu%7cb9bbf970836e444eace808d3cc677abb%7c48bf86e811a24b8a8cb368d8be2227f3%7c0&sdata=r7Iaz72zblFVEZkFSQe8zETtwWp%2bmbu8XFMJwVokR2I%3d 's testing of the files you supplied, if WAIL generates a CDX with the expected contents with WARCs from sources other than WARCreate, we may need to look into this as a bug in the latter.

**Comment by machawk1** [comment]
pywb's `cdx-indexer` seems to choke on a WARC-Request record in 20160822193710321.warc but gets through 20160822124809108.warc with success. Per @N0taN3rd's report and my own verification, the offset at 853328 appears to be the problem. This corresponds to the record that starts with:

```
WARC/1.0
WARC-Type: request
WARC-Target-URI: https://www.googleapis.com/oauth2/v2/IssueToken
WARC-Date: 2016-08-22T19:37:10Z
WARC-Concurrent-To: <urn:uuid:3bb0ec79-2469-fe7c-80a4-bd39b480737b>
...
```

...which I determined using [Hex Fiend](http://ridiculousfish.com/hexfiend/) on OS X, as many other tools are unreliable with content lengths and byte counts due to binary data.

WARCreate may not be calculating the Content-Length in the WARC header (NOTE: different from the Content-Length in an HTTP response), which is causing the cdx-indexer to fail hard and not index the remaining content in the WARC.

**Comment by N0taN3rd** [comment]
closing per WAIL 1.2.0-Beta2
