### ISSUE TITLE
Consider alternative crawling and playback engines

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#46]
As we have discussed, including tools other than Heritrix and OpenWayback for archiving and playback would make WAIL even more useful. Having a list of these, barriers in integrating them, and other related discussion would help in making this possible. Such a list is probably more suitable as a wiki page, but I figured I would add it here as a task to get your comment, @N0taN3rd .

Relevant Linkage
- https://github.com/ikreymer/pywb
- https://github.com/ludios/grab-site
- https://github.com/internetarchive/brozzler
- https://github.com/internetarchive/warcprox

**Comment by N0taN3rd** [comment]
@machawk1 I really like the idea of using pywb from using it on my own machine. 
Using of pyinstaller is not to bad(for my personal os linux).  Tried cross compilation  but did not investigate further when link errors showed up. 

The crawlers have their own dependencies like native wget,  brozzler from precursury inspection looks promising but found a snipet in the code base that looked for Chrome explicitly assuming it was on Mac OS.  Besides that trying out brozzler to see if my precursory glance is correct should happen soon(hopefully).

**Comment by machawk1** [comment]
@N0taN3rd As far as I know, pyinstaller does not do cross-compilation. This should not really be an issue, as we have all supported OS's at our disposal.

You may want to file a bug w/ Brozzler on the OS dependency. I have not worked with it extensively but it would definitely be time well-spent doing so.

The point of this ticket is really to have a Wishlist of the other tools / techs / libraries we want to add to WAIL. Even if some are "pie in the sky", a structured discussion about each tool would be worthwhile.

**Comment by N0taN3rd** [comment]
closing per [1.2.0-beta2](https://github.com/N0taN3rd/wail/releases/tag/1.2.0-beta2) and Pywb
