### ISSUE TITLE
UI: No message included in Notification for reindexing success

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#53]
![screen shot 2016-08-30 at 5 17 19 pm](https://cloud.githubusercontent.com/assets/2514780/18107391/aae45ec2-6ed5-11e6-80fe-94d74c31ff2a.png)

**Comment by machawk1** [comment]
Does the "Force Reindexing" button or a similar UI element exist in the current version, @N0taN3rd ?

**Comment by N0taN3rd** [comment]
@machawk1 I believe it was lost when redoing the ui portion to be honest. 
It will be returning once the add warcs section is cleaned up.

**Comment by N0taN3rd** [comment]
closing as per WAIL 1.2.0-Beta2
