### ISSUE TITLE
Crawl Submissions and Monitoring is hit and miss

### ISSUE THREAD

**Issue by N0taN3rd** [N0taN3rd/wail#55]
Currently once a crawl is started an fs monitor is created which looks for changes on progress-statistics.log for the latest run for a job.
If the monitor fails to "hook?" onto the file at the right time the ui will not be updated.

Heritrix using its REST api returns 303's if replying at all which can be misleading(notifications on all steps of a crawl is now shown) if it fails.

**Comment by N0taN3rd** [comment]
@machawk1 
How much of an wait time do you feel is acceptable for an confirmation that an job action has been completed?
It is becoming apparent that WAIL needs to work harder at checking the success/failure of heritrix actions. 
We have discussed scrapping the heritrix ui before, but now I feel that would be the most sure way to see if a job 
has been launched if low latency for confirmations is desired.

**Comment by machawk1** [comment]
@N0taN3rd Based on empirical observation from other apps, an action I perform seems irrelevant if no feedback is given within 3-5 seconds. Even a status update to the progress of an action, particularly those that take a long time, is enough to give me the assurance that something is happening but taking a while.

**Comment by N0taN3rd** [comment]
@machawk1 Ok then on the notification currently I think the way they are worded "Building/Launching Heritrix ..." is more indicative that WAIL is the doing all the work not heritrix. 

In order to keep the users apprised of what is going on ( especially for actions > 3-5s) rewording notifications to be along the lines of "Submitting Job Build Request To Heritrix" 
would convey that these operations may take some time better than is done currently. 

Thoughts?

**Comment by machawk1** [comment]
@N0taN3rd I'm not sure how specific you should get on the behind-the-scenes processes in WAIL, particularly with what Heritrix is doing. Rather, say what WAIL is "doing", even if it's delegating Heritrix to build the job, WAIL is "building the job" in the same way a user "builds the job", "compiles code", or any similar agent-based action.

Something like "Building Crawl Job..." is succinct and granular enough that messages like these should complete (or fail), thus allowing the message to change and convey progress of the operation more quickly.
