### ISSUE TITLE
Creating new collection causes error to display

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#59]
![screen shot 2016-12-01 at 10 47 46 pm](https://cloud.githubusercontent.com/assets/2514780/20822369/34716c6c-b818-11e6-8753-c0a0db4583bd.png)

V. 1.0.0-rc.2.9.25 @N0taN3rd

**Comment by N0taN3rd** [comment]
@machawk1 was the name of the collection containing a space by any chance?

**Comment by machawk1** [comment]
@N0taN3rd I'm not sure but when I create a new collection w/o any spaces, the error does not occur, so that could very well be the issue.

**Comment by N0taN3rd** [comment]
@machawk1 that's an issue. 
I can correct that by adding underscores to the collection name or restrict naming to only single word names.
Both options are not ideal but are a work around to this 
```shell 
wb-manager -init "test test"
```
![wbmannospaces](https://cloud.githubusercontent.com/assets/8648317/20822872/65f77232-b81c-11e6-94ca-f93a0bd1f0af.png)

**Comment by machawk1** [comment]
@N0taN3rd I am wondering if it would be best to do this in the WAIL UI so the user expects the collection name to have underscores, e.g., when a space is typed, instead insert an "_", potentially with a warning elsewhere about the limitation.

**Comment by N0taN3rd** [comment]
closing per 1.2.0-beta2.
will re-open if this becomes and issue again
