### ISSUE TITLE
Cannot create new collection

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#63]
When I enter all fields without any spaces, a red error popup says, "Creating new collection MyCollection for Error: spawn /bin/sh ENOENT"

**Comment by N0taN3rd** [comment]
@machawk1 currently the only change to this section was a check to see if spaces are in the collection name and if so not alow creation to address #59 
To address  #62 and this one a rewrite is in order using [redux-form](https://github.com/erikras/redux-form) which has proved itself to be more reliable for these situations
