### ISSUE TITLE
Adding seed for Page-Only archiving doesn't add to collection

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#66]
I added two test seeds for page-only archiving:
* www.freemasonstreet.org
* http://www.cs.odu.edu/~mweigle/

I see entries for them in the log ("Info: Archiving www.freemasonstreet.org for default Now!"), but in my collection, I have 0 seeds and no way to check on their progress.

**Comment by weiglemc** [comment]
Adding a page-only seed worked just fine if I already had something in the collection that I'd archived with Heritrix.

**Comment by N0taN3rd** [comment]
closing per WAIL 1.2.0-Beta2
