### ISSUE TITLE
Adding WARCs from filesystem failing

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#69]
All of these could be because I updated from 1.0.1 to 1.0.2 without first removing 1.0.1?

When adding WARCs from filesystem, after I choose the seed to add, I get the error
"Unable to add warcs to the collection default because [object Object]"

Happens for WARCs created with WARCreate and in previous version of WAIL.

**Comment by N0taN3rd** [comment]
closing per 1.2.0-beta2
