### ISSUE TITLE
Error message: Uncaught exception

### ISSUE THREAD

**Issue by realtrueheather** [N0taN3rd/wail#70]
I left WAIL idle for approx 10 minutes after a crawl and received this error message. 
![screen shot 2017-02-14 at 10 04 23 am](https://cloud.githubusercontent.com/assets/22311030/22934501/347d7538-f29d-11e6-8a26-f63e3d941388.png)

**Comment by N0taN3rd** [comment]
@realtrueheather thank you for reporting this.
The error it is reporting is odd for occurring when WAIL is left idle.
What version of WAIL did that happen on and have you been able to use WAIL after this occurred without the same notification?

**Comment by N0taN3rd** [comment]
closing per 1.2.0-beta2
