### ISSUE TITLE
WAIL on OS X 10.10

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#75]
Running an older version of OS X (10.10).  Got this message when I tried to create a new collection.
![screen shot 2017-04-11 at 7 52 53 pm](https://cloud.githubusercontent.com/assets/5034094/24935531/a3341bba-1ef0-11e7-97a5-6d3728e4b65f.png)

**Comment by weiglemc** [comment]
Recent updated worked on OS X 10.10

**Comment by weiglemc** [comment]
Maybe that didn't fix it.  After the crawl ended, I got this error:

Error: Could Not Add Warcs to default because Error loading Python lib '/Applications/WAIL.app/Contents/Resources/app/bundledApps/pywb/Python': dlopen(/Applications/WAIL.app/Contents/Resources/app/bundledApps/pywb/Python, 10): Symbol not found: _clock_getres Referenced from: /Applications/WAIL.app/Contents/Resources/app/bundledApps/pywb/Python (which was built for Mac OS X 10.12) Expected in: /usr/lib/libSystem.B.dylib in /Applications/WAIL.app/Contents/Resources/app/bundledApps/pywb/Python

**Comment by N0taN3rd** [comment]
Pyinstaller issues with hooks finding the dlib library on OSX: 
- [#2544](https://github.com/pyinstaller/pyinstaller/issues/2544)
- [#2460](https://github.com/pyinstaller/pyinstaller/issues/2460)

Solution maybe to install python + pywb on system rather than using it until issues are resolved
