### ISSUE TITLE
Invalid URL for Wail-WarCreate

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#76]
Tried to archive www.freemasonstreet.org using Page Only, but got an error with Wail-WarCreate:

There was an error while using Wail-WarCreate ERR_INVALID_URL. Resorting to using Heritrix

(Also, we should change the capitalization on this to WARCreate.)

**Comment by realtrueheather** [comment]
I also had this issue for 3 different urls, all using Page Only
![screen shot 2017-04-22 at 12 39 38 pm](https://cloud.githubusercontent.com/assets/22311030/25306426/f0b32aa8-275a-11e7-8e04-5e535e45266e.png)

**Comment by machawk1** [comment]
I was able to replicate the issue @weiglemc reported with the same URI (`www.freemasonstreet.org`) using v1.1.0beta on macOS 10.12.4.

I repeated the process but added `http://` before `www.freemasonstreet.org`. WAIL no longer reported the error in a notification and the crawl looks to have completed successfully. With this in mind, the error might be attributed to URI parsing with particular emphasis on checking if a scheme is present.

![screen shot 2017-05-10 at 10 54 11 am](https://cloud.githubusercontent.com/assets/2514780/25905118/2037ea62-356f-11e7-9d6f-331c921dcb73.png)

**Comment by N0taN3rd** [comment]
@machawk1 @weiglemc @realtrueheather
The scheme parsing was indeed the issue. The when "loading" the URI-R into the [webview](https://electron.atom.io/docs/api/webview-tag/#webviewloadurlurl-options) chokes when the URI-R is schemeless for some reason. 
Commit 2d26cb5 address this issue and expect to have a new release with the fix by end of the week bringing in fixes to #77 #70 #73.
