### ISSUE TITLE
META: Create repo issues template

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#78]
I think it would be beneficial for this repo to have a GitHub issue template:

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

A few GH issue reports, while helpful in debugging, might be obsolete due to the problem already being fixed. Fields like OS, version of WAIL (with guidance on how to find this), URI being crawled, etc. could be used to replicate bugs. Thoughts, @N0taN3rd ?

**Comment by N0taN3rd** [comment]
@machawk1 that is a really great Idea. 
I believe I have seen other projects that have done this but never thought about doing so for this project.
