### ISSUE TITLE
Missing image on acid test single-page capture

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#85]
### Are you submitting a **bug report** or a **feature request**?

Bug.

### What is the current behavior?

Missing image on acid test at http://acid.matkelly.com

### What is the expected behavior?
All blue squares.

### What's your environment?

WAIL 1.2.0-beta, macOS 10.12.5

### Other information

![screen shot 2017-07-19 at 11 03 24 pm](https://user-images.githubusercontent.com/2514780/28398736-99f51764-6cd6-11e7-9ebf-9dd54bcc4646.png)

**Comment by N0taN3rd** [comment]
@machawk1 hehe believe I got bit by you gotta interact with the page!
Where to put the [scroll](https://github.com/N0taN3rd/wail/blob/wail-electron/wail-archiver/pageEvals/helpers.js#L71) [the page option](https://github.com/N0taN3rd/wail/blob/wail-electron/wail-archiver/electronArchiver.js#L175)??? 
Add additional option with scroll option (`Page Only` and `Page Only and Scroll`) or have a checkbox that only appears with these crawls

**Comment by machawk1** [comment]
You may simply want to scroll by default, wait a few seconds, see if the DOM has changed and if so, repeat. This could also put you in an infinite loop w/ sites like Twitter.

**Comment by N0taN3rd** [comment]
@machawk1 that maybe the best option for now 
Might also solve some of the wail-ui issues concerning how fast preservation happens.

**Comment by machawk1** [comment]
If you are going to use the above scheme, put a hard limit on the number of scroll iterations to ensure the actual preservation part is performed after the UI of the page has settled.

**Comment by N0taN3rd** [comment]
@machawk1 scrolling is bound by the initial `document.documentElement.scrollHeight` and a time duration of 4 seconds https://github.com/N0taN3rd/wail/blob/wail-electron/wail-archiver/pageEvals/helpers.js#L73 :smiley:

**Comment by N0taN3rd** [comment]
@machawk1 fixed and updated release binary
![screen shot 2017-07-20 at 2 20 27 am](https://user-images.githubusercontent.com/8648317/28403279-18e7dbfe-6cf2-11e7-95a3-15860790d633.png)
