### ISSUE TITLE
WAIL crawls pane shows nothing but gray when no crawls are ongoing

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#86]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

Before firing off any crawls or if none are ongoing, the "Wail crawls" selection in the navigation shows a panel with just a gray background and no other information. 

### What is the expected behavior?
Some indicator that there are no ongoing crawls would be useful.

### What's your environment?

WAIL 1.2.0-beta, macOS 10.12.5

**Comment by N0taN3rd** [comment]
@machawk1 yes it is.......
Getting wail-ui to not crumble with the update speed and getting Pywb to play nice with adding WARC during these crawls was priority.
I still not sure with what to with this section.... 
Page only crawls are over so fast.

**Comment by machawk1** [comment]
@N0taN3rd Even something as simply as a message saying, "There are currently no running crawls." would give some indication that the grey block is not a bug. As an added bonus, you could also have a link saying "Start one now!" that directs the user to the respective part of the WAIL UI.
