### ISSUE TITLE
Get WAIL-Electron added to Electron apps directory

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#87]
See the [Apps Built with Electron page](https://electron.atom.io/apps/).

https://github.com/electron/electron links to https://electron.atom.io/apps/

WAIL-Electron ought to be listed at https://electron.atom.io/apps/.

https://github.com/electron/electron-apps/blob/master/contributing.md

Ping @N0taN3rd

**Comment by N0taN3rd** [comment]
Thanks @machawk1 for the ping!

PRs:
[electron/electron-apps](https://github.com/electron/electron-apps/pull/270)
[sindresorhus/awesome-electron](https://github.com/sindresorhus/awesome-electron/pull/474)

**Comment by N0taN3rd** [comment]
@machawk1 
PRs:
[electron/electron-apps](https://github.com/electron/electron-apps/pull/270) :+1: 
[sindresorhus/awesome-electron](https://github.com/sindresorhus/awesome-electron/pull/474) :-1:

**Comment by machawk1** [comment]
@N0taN3rd The "I need to be pickier" comment in the latter is discouraging. Watch for others in that repo that get the same response (rejected PRs) and put it on your own fork.
